---
title: "Efficient method to convert raster to polygons & Merge adjacent polygons"
output: html_document
---
## Define the function of converting raster to polygon efficiently

```{r defineFun1}

# need to have GDAL installed, and find out the full path to GDAL\\gdal_polygonize.py
ra2ply <- function(x, outshape=NULL, gdalformat = 'ESRI Shapefile',pypath=NULL) {
  
  require(raster)
  require(rgdal)
  
  dir=getwd()
  on.exit(setwd(dir))
  setwd(dirname(pypath))
  
  if (!is.null(outshape)) {
    outshape <- sub('\\.shp$', '', outshape)
    f.exists <- file.exists(paste(outshape, c('shp', 'shx', 'dbf'), sep='.'))
    if (any(f.exists))
      stop(sprintf('File already exists: %s',
                   toString(paste(outshape, c('shp', 'shx', 'dbf'),
                                  sep='.')[f.exists])), call.=FALSE)
  } else outshape <- tempfile()
  
  writeRaster(x, {f <- tempfile(fileext='.tif')})
  rastpath <- normalizePath(f)
  
  system2('python', args=(sprintf('"%1$s" "%2$s" -f "%3$s" "%4$s.shp"',
                                  pypath, rastpath, gdalformat, outshape)))
  shp <- readOGR(dirname(outshape), layer = basename(outshape))
  crs(shp)=crs(x)
  
  # remove last polygon if the last polygon have the same extent with input raster
  n=dim(shp)[1]
  if (extent(shp[n,])==extent(x)){shp=shp[-n,]}
  return(shp)
  
  setwd(dir)
}

```

## Run the function
```{r Raster2Poly}
setwd("C:/Users/liang/Desktop/optimization/control/")

tif=list.files(".",".tif$")
library(raster)
ra=raster(tif[1])
ra2=ra

## sign pixels of interest with the same value, as the method tends to classify connected pixels with very different values into different polygons 
ra2[ra2>0]=1


polys=ra2ply(ra2, outshape = NULL,pypath = "C:\\Program Files\\GDAL\\gdal_polygonize.py")
polys

t1=system.time(
  {p=ra2ply(ra, outshape = NULL,pypath = "C:\\Program Files\\GDAL\\gdal_polygonize.py")}
)

## compare with the raster2polygons functions provided by raster package
t2=system.time(
  {p2=rasterToPolygons(ra,dissolve = T)}
)

t1 
t2 

#writeOGR(p,".","effi2",driver = "ESRI Shapefile")
#writeOGR(p2,".","raToply",driver = "ESRI Shapefile")
```


## Still, similar with ArcGIS rasterToPolygon, pixels connected along a diagonal line are classified into different polygons
## Here, develop a function to merge polygons within a given distance. Below are two different functions that can do the job nicely.

```{r DefineFun2}
### function 1 based on distance
merge_Adjacent_Poly1 = function(polys,dis){
  
  require(rgeos)
  require(maptools)
  disMatr=gDistance(polys,polys,byid=T)
  disMatr=as.data.frame(disMatr)
  n=dim(disMatr)[1]
  
  polys$id=1:n
  
  for (i in 1:n){
    polys$id[disMatr[,i]<=dis]=polys$id[i]
  }
  
  groups=polys$id
  polys2=unionSpatialPolygons(polys,groups)
  n2=length(polys2)
  
  polys3=SpatialPolygonsDataFrame(polys2,data=data.frame(ID=1:n2), match.ID = F)
  return(polys3)
  
}  

## function 2 use clustering method
merge_Adjacent_Poly2 = function(polys,dis){
  
  require(rgeos)
  require (maptools)
  
  disMatr=gDistance(polys,polys,byid=T)
  n=dim(disMatr)[1]
  
  clust=hclust(as.dist(disMatr>dis),method="single") # revised from smart solution from https://gis.stackexchange.com/users/865/spacedman
  groups=cutree(clust,h=0.5)
  
  
  polys2=unionSpatialPolygons(polys,groups)
  n2=length(polys2)
  
  polys3=SpatialPolygonsDataFrame(polys2,data=data.frame(ID=1:n2), match.ID = F)
  return(polys3)
}  

```

``` {r Merge}
t3=system.time(
  {
    plyDF1=merge_Adjacent_Poly1(polys,0)
  }
)

t4=system.time(
  {
    plyDF2=merge_Adjacent_Poly2(polys,0)
  }
)

t3 # 309 features in polys
t4 # 309 features in polys

```
